### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by khaledAltuwaijri** [fdemmer/django-weasyprint#11]
I am wondering if you guys are going to support python 3.6 soon, could you give me some insight on this subject?

**Comment by SalahAdDin** [comment]
Do you have problems with this?

**Comment by fdemmer** [comment]
@khaledAltuwaijri all Python versions supported by Django and WeasyPrint are supported. That includes Python 3.6.

If you have a specific issue, please provide details.
