### ISSUE TITLE
Recursion error with large file.

### ISSUE THREAD

**Issue by bassasaurus** [fdemmer/django-weasyprint#18]
Traceback

https://pastebin.com/eAHZKiY1

I have a file with ~3.5k lines that keeps giving me a maximum recursion error.

It seems to concern this line in particular

`/lib/python3.6/site-packages/weasyprint/formatting_structure/build.py" in element_to_box
  155.             child_element, style_for, get_image_from_uri, base_url, state))`

This is my first time reporting a bug - forgive me for possibly not doing it properly.

P.S. I really like this package -  thank you!

**Comment by fdemmer** [comment]
as the error occurs in weasyprint code (/lib/python3.6/site-packages/**weasyprint**/formatting_structure/build.py) and django-weasyprint is just a thin wrapper to use weasyprint with class based views, you should probably open an issue with [weasyprint](https://github.com/Kozea/WeasyPrint) and provide the html document that is causing the problem in addition to the trace.
