### ISSUE TITLE
Signature of inherited functions

### ISSUE THREAD

**Issue by suriya** [fdemmer/django-weasyprint#2]
I was extending your code a bit and I noticed a minor issue. I am not sure if this really is an issue, but I thought I'd bring it to your attention and let you decide.

In 
https://github.com/dekkers/django-weasyprint/blob/master/django_weasyprint/views.py#L35 the signature of render_to_response does not match that of its super class implementation TemplateResponseMixin.render_to_response https://github.com/django/django/blob/stable/1.6.x/django/views/generic/base.py#L119

Similarly for PDFTemplateResponse.**init**.

Thank you for your work.

**Comment by fdemmer** [comment]
Thank you for your comment! The signature is now the same.
