### ISSUE TITLE
Passing Images in Templates

### ISSUE THREAD

**Issue by supermanzer** [fdemmer/django-weasyprint#20]
I am attempting to include a logo image for my PDF.  The `img` tag that displays the logo in my HTML is as follows:

    <img class="logo" src="/static/images/logo.png" alt="Nordic Naturals">

Is there a way we can pass the image file to the PDF similar to identifying the CSS rules to be followed?

**Comment by fdemmer** [comment]
you should use `{% load static %}` in templates.

using css and images from your static files should "just work", if the files are actually served by a http server (`runserver` or production setup; try rendering the template as html output and check the urls), eg:

```
{% load static %}

<link rel="stylesheet" href="{% static "css/app.css" %}" />
<img src="{% static "img/placekitten-140.jpeg" %}" alt="placekitten">
```

that's a feature of [weasyprint](https://weasyprint.org/) itself, it fetches required files automatically ([docs](https://weasyprint.readthedocs.io/en/stable/features.html#urls), [code](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/urls.py#L204)). passing a list of css files directly to weasyprint via `pdf_stylesheets` is [completely optional](https://weasyprint.readthedocs.io/en/stable/tutorial.html#stylesheet-origins) and usually not necessary.
