### ISSUE TITLE
Static images not fetched on production server

### ISSUE THREAD

**Issue by josvleeuwen** [fdemmer/django-weasyprint#21]
Something seems to be going wrong when fetching urls from a static, maybe because my static_url is on a subdomain?

I have my pdf rendering perfectly fine locally with static_url:
```STATIC_URL = '/static/'```

However on my production server the images seem not to load with this static url:

```STATIC_URL = 'https://static.domain.com/'```

I'm using django-weasyprint 0.5.4

I'm using a simple TemplateView with WeasyTemplateResponseMixin:
```
class GenerateSTPContractPDF(WeasyTemplateResponseMixin, TemplateView):
    template_name = 'contract.html'
```

And in my template I'm loading the images from static:
```
{% load staticfiles %}
<img src="{% static 'myimage.jpg' %}">
```

Is this a bug or am I doing something wrong?

**Comment by fdemmer** [comment]
you should not use `staticfiles` but `static` ([docs](https://docs.djangoproject.com/en/2.1/howto/static-files/)).

as described in #20 loading files is a weasyprint feature. if the url in the rendered template is correct and there is a server providing the files at that url, it should work.

try rendering the view without the `WeasyTemplateResponseMixin` and see if the images load.
