### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2

### ISSUE THREAD

**Issue by Mr-Manna** [fdemmer/django-weasyprint#24]
I am having this issue. But I have already installed GTK on windows using pacman -S mingw-w64-x86_64-gtk3

**Comment by fdemmer** [comment]
django-weasyprint is just a wrapper for weasyprint; this issue is not related to django-weasyprint.

follow the weasyprint instructions for windows to the dot, "Really carefully. Don’t cheat.": https://weasyprint.readthedocs.io/en/stable/install.html#windows

**Comment by avkhub** [comment]
@Mr-Manna Were you able to get around this error ```OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2  ``` using ```Weasy-Print ``` - i am javing the same issue. Please let me know
