### ISSUE TITLE
how to configure nginx to deal with django_weasyprint requests

### ISSUE THREAD

**Issue by ngazzaz** [fdemmer/django-weasyprint#25]
thats the error i get
`Failed to load image at "http://localhost/static/images/Logo.svg" (URLError: <urlopen error [Errno 99] Cannot assign requested address>)`

cause nginx doesn't GET the images instead it redirects to the url

nginx configurations:
```
upstream hello_django {
    server web:8000;
}

server {
    listen   80;

    location /static/ {
        autoindex on;
        alias   /code/static/;
    }

    location /media/ {
        autoindex on;
        alias   /code/media/;
    }

    location / {
        proxy_pass http://hello_django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    #For favicon
    location  /favicon.ico {
        alias /code/assets/favicon.ico;
    }

    # Error pages
    error_page 404 /404.html;
    location = /404.html {
        root /code/templates/;
    }
}


```

**Comment by freezed** [comment]
I think your issue has nothing to do with `django-weasyprint`.

However, look at my `Nqinx` _static conf_ which is different than yours :
https://gitlab.com/free_zed/myasb/blob/master/templates/nginx_site.j2

**Comment by fdemmer** [comment]
I agree, this outside the scope of django-weasyprint. weasyprint's default [URL fetcher ](https://weasyprint.readthedocs.io/en/stable/tutorial.html#url-fetchers) uses [urllib](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) to fetch resources, which follows redirects automatically.
