### ISSUE TITLE
Imagefield not showing due to LoginRequiredMiddleware

### ISSUE THREAD

**Issue by markdimi** [fdemmer/django-weasyprint#26]
Hello. New to django-weasyprint. My problem resided with weasyprint initially because it couldn't render a `model.imagefield` after I implemented a middleware that required login to view all the content. 

After that django-weasyprint came to my attention. I hastily implemented a solution but the image still doesn't show.  Any help?

**Comment by markdimi** [comment]
Well, maybe I could resolve this issue with django-weasyprint, but I found out that by using the `file:` prefix and the path of the imagefield it fetches the data smoothly.

For fellow midnight googlers:

`<img src='file: {{ model.image.path }}'>`

Also probably you have to also use `base_url=request.build_absolute_uri()` on the view function.

**Comment by fdemmer** [comment]
weasyprint's [URL fetchers](https://weasyprint.readthedocs.io/en/stable/tutorial.html#url-fetchers) do not support authentication.

django-weasyprint provides a custom URL fetcher, that reads "file:" URLs directly from disk: https://github.com/fdemmer/django-weasyprint/blob/master/django_weasyprint/utils.py
