### ISSUE TITLE
How to combine some PDF files at the end of the rendered HTML to PDF ?

### ISSUE THREAD

**Issue by pulse-mind** [fdemmer/django-weasyprint#31]
At this time I am using django weazyprint to render an HTML to PDF. It works fine, thank you :).
I'd like to add at the end of this PDF some PDF files generated by another software. 
Is it possible ? And how to proceed please ?

**Comment by freezed** [comment]
Don't you use `views` in django?

**Comment by pulse-mind** [comment]
Yes I do.

**Comment by freezed** [comment]
This is not a `weasyprint` matter : add whatever you need in your `view` and django will render it.

**Comment by fdemmer** [comment]
You could use [pdfrw](https://github.com/pmaupin/pdfrw/) to append the pages from your "other PDF" to the one generatey by weasyprint. Not a weasyprint or django-weasyprint issue.
