### ISSUE TITLE
OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by Gilbishkosma** [fdemmer/django-weasyprint#32]
no library called "libcairo-2" was found
cannot load library 'libcairo.so': Error loading shared library libcairo.so: No such file or directory
cannot load library 'libcairo.2.dylib': Error loading shared library libcairo.2.dylib: No such file or directory
 cannot load library 'libcairo-2.dll': Error loading shared library libcairo-2.dll: No such file or directory
I have only installed django-weasyprint and it is showing this error when i try to use it.

**Comment by Gilbishkosma** [comment]
Do i need to install other dependencies too?

**Comment by mrbrazzi** [comment]
Did you install required dependencies for WeasyPrint in your OS?, check this [https://weasyprint.readthedocs.io/en/latest/install.html](https://weasyprint.readthedocs.io/en/latest/install.html)
