### ISSUE TITLE
Permit undefined MEDIA_URL and STATIC_URL

### ISSUE THREAD

**Issue by pauloxnet** [fdemmer/django-weasyprint#34]
In [`django_url_fetcher`](https://github.com/fdemmer/django-weasyprint/blob/master/django_weasyprint/utils.py#L18) permit to have undefined `MEDIA_URL` and `STATIC_URL`.

**Comment by fdemmer** [comment]
Can you describe the scenario, why you need this in more detail please?

Django sets `MEDIA_URL=''` and `STATIC_URL=None` by default in `global_settings.py`, so any project should have it.

Have you tried simply not using any URL starting with "file:"? In that case the code-path using `MEDIA_URL` and `STATIC_URL` is never used.

**Comment by mmazzocchetti** [comment]
When MEDIA_URL='' and STATIC_URL is defined, MEDIA_URL is always matched even for STATIC_URL prefixed urls.
