### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by browniebroke** [fdemmer/django-weasyprint#5]
With the xhtml2pdf project being [recently abandoned](https://github.com/xhtml2pdf/xhtml2pdf), they suggest using Weasyprint instead, so I started digging for a wrapper for Django and found this project.

Seeing that it looks quite inactive as well, I looked at the forks, and found @fdemmer [fork](https://github.com/fdemmer/django-weasyprint) which has continued the project, and looks much more active. Then I searched on [on PyPi](https://pypi.python.org/pypi/django-weasyprint), but the package owner seems to be someone else, is that you @graingert maybe?

Which one is still maintained? Am I right in assuming that the Pypi package is not the same code as @fdemmer's fork? If so, is there any plan in consolidating ownership of the repository and Pypi package?

If none of you is maintaining them anymore, no worries, I'll do my own, just wanted to check before jumping to something abandoned.

**Comment by fdemmer** [comment]
with my fork i attempted to make the api work/look more like https://github.com/nigma/django-easy-pdf

development somewhat stalled, but i am actively using my fork in a project as it is now.

there is at least one `#TODO` in the code that should be resolved and i was planning to also rename all the view mixins/classes to actually match those of django-easy-pdf (ie not use the "weasy" wording; easier potential drop in replacement). that should be done before doing a release.

i am not owner on pypi. never maintained a package there myself yet. not super keen on taking ownership, but would love to see my changes merged back into a new proper release.

**Comment by graingert** [comment]
If you start maintaining something I'll give you the name on PyPI

**Comment by browniebroke** [comment]
I totally understand if you're a bit reluctant on taking ownership of a Pypi package, but if you need a guide to get started, I found [this resource](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) quite useful. It's lengthy, more because being detailed, than being complex, but yea, it can seems like a commitment...

Anyway, thanks for the quick response guys 👍  for now I'll just use `pip install -e git+git://github.com/fdemmer/django-weasyprint.git@1d7f42aae5751f077490173d3d55d9e7036ba5e0#egg=django-weasyprint`

**Comment by graingert** [comment]
pip install https://github.com/fdemmer/django-weasyprint/archive/1d7f42aae5751f077490173d3d55d9e7036ba5e0. tar.gz#egg=django-weasyprint

Is much faster and supports pip cache
