### ISSUE TITLE
Release the main branch for compatibility with weasyprint 53  

### ISSUE THREAD

**Issue by foarsitter** [fdemmer/django-weasyprint#56]
Hey there, 

It looks to me the changes made in the main branch are fixing the issues with weasyprint 53. It should be awesome to have a new release so I can ditch my workarounds. 

Cheers!

**Comment by fdemmer** [comment]
https://pypi.org/project/django-weasyprint/2.0.0/

**Comment by foarsitter** [comment]
Thank you for your time and quick response!
