### ISSUE TITLE
Very verbose logs

### ISSUE THREAD

**Issue by Nasjoe** [fdemmer/django-weasyprint#58]
Hi !

Thanks a lot for you work. It's amazing and very usefull for us.
I try to install it within my stack, and with the last update ( from django-weasyprint 1 to 2.1.0 ), the ouput logger.info is become very very verbose on each pdf creation :)

Did you know how to calm down the log ?
Thanks !

**Comment by vdveldet** [comment]
since this is based on the default logger you may use.

```
# start reduce error on weasyprint
logger = logging.getLogger("weasyprint")
logger.addHandler(logging.NullHandler())
logger.setLevel(40) # Only show errors, use 50
# stop reduce error on weasyprint
```

**Comment by fdemmer** [comment]
`django-weasyprint` does not emit any logging. here is some `weasyprint` documentation on logging: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html?highlight=logging#logging
