### ISSUE TITLE
Take over PyPI package 

### ISSUE THREAD

**Issue by graingert** [fdemmer/django-weasyprint#6]

**Comment by pkaczynski** [comment]
Any chance on that?

**Comment by robvdl** [comment]
@fdemmer have you considered this offer? The version on pypi is from 2013 v0.1 and it seems the original author is asking.

**Comment by Asday** [comment]
Any word on this?

**Comment by graingert** [comment]
@Asday nope. @fdemmer do you want to maintain https://pypi.python.org/pypi/django-weasyprint ? I can add you.

**Comment by fdemmer** [comment]
sure, if noone else is interested! i cannot promise much time for maintenance, but will push a new version to pypi asap. thanks @graingert!

**Comment by graingert** [comment]
@fdemmer sweet, what's your PyPI id?

**Comment by fdemmer** [comment]
"fdemmer" ;)

**Comment by graingert** [comment]
@fdemmer done

**Comment by Asday** [comment]
Excellent, thanks for jumping on this, guys.  :heart:
