### ISSUE TITLE
cannot display script output from javascript

### ISSUE THREAD

**Issue by wawan-sulisstia** [fdemmer/django-weasyprint#62]
I'm doing a "Total" sum on multiple tables using javascript. But when I export, the script cannot be read in the PDF file. Whereas previously the script was read on a Web page.

Is there a solution?

**Comment by fdemmer** [comment]
WeasyPrint does not support Javascript.

> ... WeasyPrint’s scope is much smaller: there is no user-interaction, no JavaScript, no live rendering (the document doesn’t changed after it was first parsed) and no quirks mode (we don’t need to support every broken page of the web.)

-- https://doc.courtbouillon.org/weasyprint/stable/going_further.html?highlight=javascript
