### ISSUE TITLE
Multi-process support?

### ISSUE THREAD

**Issue by wiltzius** [fdemmer/django-weasyprint#7]
Hey folks,

I'm currently struggling with https://github.com/Kozea/WeasyPrint/issues/167 which is a bug in upstream weasyprint -- it segfaults when run in a forked child process. This precludes using forked WSGI servrs like gunicorn or uwsgi.

Have y'all found a workaround for that to make this work under Django regardless of the WSGI server process model, by chance?

Thanks,
Tom

**Comment by fdemmer** [comment]
I've been following the upstream issue, but it has never happened to me. I am going to close this too, since the upstream issue was (hopefully) fixed.
