### ISSUE TITLE
speed problems

### ISSUE THREAD

**Issue by fjbardelli** [fdemmer/django-weasyprint#73]
Hello, how are you, sorry for the inconvenience.

I am generating a PDF of approximately 26 pages, it is a render of a table with many rows, for the aesthetics of the table and the report I use Boottrap 3, it does it very well but it is very very slow, is there something I am doing wrong or is it normal , I tried several ways to use weasyprint and none of them achieved more speed. It takes a few more or 46 seconds less, and if there are more pages it will take up to several minutes.

Thank you

**Comment by liZe** [comment]
Hi!

It’s probably a problem with WeasyPrint, not Django-WeasyPrint. Could you please try to share a HTML page showing that problem, so that we can find why it’s slow?

**Comment by fjbardelli** [comment]
If there is no problem I will share the code with you

**Comment by fjbardelli** [comment]
If there is no problem I will share the code with you
[diario.html.txt](https://github.com/fdemmer/django-weasyprint/files/13400630/diario.html.txt)


 ```1
        @action(methods=['get'], detail=False)
            def pdf(self, request, *args, **kwargs):
                inicio = datetime.now()
                qs = get_diario(self.ent_periodo.pk, self.request.GET.get(
                    'fecha_after'), self.request.GET.get('fecha_before'))
        
                data = self.serializer_class(qs, many=True)
                e: EntidadPeriodo = EntidadPeriodo.objects.get(
                    pk=request.GET.get('entidad'))
                time_data = datetime.now()
                context = {
                    'asientos': data.data,
                    'desde': datetime.strptime(request.GET.get('fecha_after'), "%Y-%m-%d"),
                    'hasta': datetime.strptime(request.GET.get('fecha_before'), "%Y-%m-%d"),
                    'entidad_periodo': e,
                }
                templete_file = 'contable/diario.html'
        
                template = get_template(templete_file)
                html_content = template.render(context)
                html = HTML(string=html_content)
                pdf_file = html.write_pdf()
        
                response = HttpResponse(content_type='application/pdf;')
                response['Content-Disposition'] = 'inline; filename=diario.pdf'
                response['Content-Transfer-Encoding'] = 'UTF-8'
                response.write(pdf_file)
        
                fin = datetime.now()
                print((time_data-inicio).total_seconds())
                print((fin-inicio).total_seconds())
                return response
```
this line is very slow   response.write(pdf_file)

Thank you very much for the reply

**Comment by liZe** [comment]
Generating a 27-page PDF with a very very long table takes less than 15s on my laptop, so it may not be the bottleneck.

> this line is very slow `response.write(pdf_file)`

Are you sure that this line is slow? Isn’t that `pdf_file = html.write_pdf()`?

**Comment by liZe** [comment]
I don’t know Django very well, but [`FileResponse`](https://docs.djangoproject.com/en/4.2/ref/request-response/#fileresponse-objects) may give better results than `HttpResponse`.

**Comment by fjbardelli** [comment]
You are right, this line pdf_file = html.write_pdf() is slow.

**Comment by liZe** [comment]
> You are right, this line pdf_file = html.write_pdf() is slow.

Less than 15s (including WeasyPrint’s import that should not happen with Django-WeasyPrint) is quite "normal" with WeasyPrint’s current limited performance. Bootstrap (uncompressed) includes more than 12,000 lines of CSS, removing it saves ~6s for me. Very long tables are known to be quite long to layout because we have to calculate the size of all cells before determining the width of each column. Using `table-layout: fixed` may help.

If your rendering takes much longer, you can try to use a more recent version of Python (there are major improvements between Python 3.8 and 3.12).

So… First of all, that’s not a problem in Django-WeasyPrint, that’s a problem of WeasyPrint, so we can close this issue. You can open a ticket in WeasyPrint to continue the discussion, but I’m afraid that there’s no silver bullet here to fix the problem.

**Comment by fdemmer** [comment]
Thank you for your support @liZe !
