### ISSUE TITLE
Potential regression with use of WEASYPRINT_BASEURL and images

### ISSUE THREAD

**Issue by laudrup** [fdemmer/django-weasyprint#74]
I have a small project that uses django-weasyprint for generating PDFs from Django templates.

It works just fine but after the latest upgrade to v2.2.1 and Weasyprint v59.0 it noticed that my tests stopped working while running in both development and production works just fine.

The issue seems to be that `WEASYPRINT_BASEURL` is no longer used as the base path for images the way it could previously be used. In my tests I use that for referring to a local path on the filesystem as can be seen [here](https://github.com/laudrup/ebbamaala/blob/f42986ac926d2b0c4ab87be6e4a86a2c0a5095c8/website/tests/test_pdf.py#L14) although it doesn't seem like this is related to overriding settings in tests.

So it seems to me like this might be a regression as the `WEASYPRINT_BASEURL` is ignored for image paths which I assume shouldn't be the case.

 I haven't done a lot of time digging into this, but it seems to me like it might be related to [this change](https://github.com/Kozea/WeasyPrint/commit/82c077b457ceade370395c6d5e29e2fcadbeffd8) in Weasyprint.

Not sure if this could be an issue in Weasyprint or django-weasyprint. It is of course also very likely that I've misunderstood something or been using the `WEASYPRINT_BASEURL` incorrectly.

I'll be happy to look more into this and perhaps extends the tests to reproduce this but it would be nice to know if this is indeed an issue before I look any further.

Thanks a lot.

**Comment by fdemmer** [comment]
That indeed is/was an issue, that became visible by the changes in https://github.com/Kozea/WeasyPrint/pull/1853. Thanks a lot for reporting it and providing the actual project to reproduce the issue :)

By retuning `redirected_url`, the [URL fetcher](https://github.com/fdemmer/django-weasyprint/blob/main/django_weasyprint/utils.py#L24) should play nicely with those changes in the next release.
