### ISSUE TITLE
function based way to print the pdf and how to debug if the styles are not working

### ISSUE THREAD

**Issue by simkimsia** [fdemmer/django-weasyprint#78]
Hi there, I am using weasyprint directly and i cannot get the styles to work.

I googled then found this and django-renderpdf.

I prefer to use django-weasyprint. my questions are:

1. can django-weasyprint have a function-based way to work? the reason is because i intend to have a backend job using celery to create the pdf
2. if the styles don't work, how to debug this issue?

btw, i am willing to pay for consultation to speed things up as well. dm me on discord kimsia#3035. I can do sponsorship as well through github if that works too.

**Comment by mikeywuu** [comment]
+1 for the function based view details.

**Comment by fdemmer** [comment]
@simkimsia do i understand correctly: you are looking for guidance on how to write a celery task, that renders a django template and saves it as pdf?

@mikeywuu is your "+1" for the same request as @simkimsia's or are you asking about [django function-style views](https://docs.djangoproject.com/en/4.2/topics/http/views/#a-simple-view)?

**Comment by simkimsia** [comment]
> do i understand correctly: you are looking for guidance on how to write a celery task, that renders a django template and saves it as pdf?

@fdemmer  yes that's correct.

**Comment by fdemmer** [comment]
@simkimsia I added a short celery task example to the README. It's pretty straight forward:

- use Django's `render_to_string()` to generate HTML
- use WeasPrint's `HTML()` and `write_pdf()` to write the PDF

The `django_url_fetcher` is the only part `django-weasyprint` provides, that might be useful outside a view context.
